### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Rian501** [code-for-nashville/glean-tennessee-web#44]
When a user arrives on the page, if they are already logged in, they should immediately see the "Submit request" page available.

When a user arrives on the page, if they are not logged in, they should see the login screen (with link to register in case they are new user)

**Comment by braindawg** [comment]
If I'm looking at this right, there's no need for a 'Home' screen. If the user's authed, we can send them to Dashboard, otherwise the logic's already there to send them to Login (if we set the route to 'protected'). So it seems like it should be as simple as changing routes.js as follows:
`{
      path: '/',
      action: ({params}) => <Home params={params} />,
      protected: false
    }`
to
`{
      path: '/',
      action: ({params}) => <Dashboard params={params} />,
      protected: true
    }`

Dynamic navbar that was just added via PR #49 should take care of setting the links appropriately. Am I missing another purpose for the 'Home' screen?

**Comment by braindawg** [comment]
PR #51 opened to make that change - not sure whether the discussion would be more appropriate on that PR or here on the issue.

**Comment by CoreyAR** [comment]
Thanks @braindawg! This has been merged!
